stages:
  - deploy

variables:
  S3_BUCKET_NAME: simple-blog-project

deploy_to_s3:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - aws --version
    - aws s3 sync frontend/ s3://simple-blog-project --delete
  only:
    - main


